apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonfly-single
  namespace: dragonfly
  labels:
    app: dragonfly
    project: consumer-project
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-single
    app.kubernetes.io/part-of: dragonfly
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dragonfly
  template:
    metadata:
      labels:
        app: dragonfly
    spec:
      containers:
      - name: dragonfly
        image: ghcr.io/dragonflydb/dragonfly:latest
        args:
          - "--dbfilename=dragonfly-backup-{timestamp}"
          - "--unixsocket=/tmp/dragonfly.sock"
          - "--snapshot_cron=0 * * * *" # Every hour
        resources:
          limits:
            memory: "16Gi"
            cpu: "24000m"
          requests:
            memory: "8Gi"
            cpu: "8000m"
        volumeMounts:
          #- name: unix-socket-volume
          #  mountPath: /tmp
          - name: data
            mountPath: /data
      volumes:
	#- hostPath:
        #    path: /tmp
        #    type: Directory
        #  name: unix-socket-volume
        - name: data
          persistentVolumeClaim:
            claimName: dragonfly-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-single
  namespace: dragonfly
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: dragonfly
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dragonfly-data-pvc
  namespace: dragonfly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

