apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-sample
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly-sample
  namespace: dragonfly-operator-system
spec:
  replicas: 1
  args:
    - "--maxmemory=32gb"
    - "--conn_io_thread_start=40"
    - "--maxclients=200000"
  resources:
    requests:
      cpu: 5
      memory: 16Gi
    limits:
      cpu: 10
      memory: 32Gi
