apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dragonfly-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dragonfly-operator-manager-role
subjects:
- kind: ServiceAccount
  name: dragonfly-operator-controller-manager
  namespace: dragonfly

